version: "3"

services:
  web:
    image: node:lts
    hostname: register.localhost
    working_dir: /var/www/html
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www/html
    ports:
      - "8081:8081"
    command: bash -c "tail -f /dev/stderr"
